categories: [Metabolomics]
description: '[W4M][LC-MS] IPO'
homepage_url: http://workflow4metabolomics.org
long_description: 'Part of the W4M project: http://workflow4metabolomics.org'
name: ipo
owner: lecorguille
