categories: [Metabolomics]
description: '[Metabolomics][W4M][LC-MS] XCMS R Package - Preprocessing - RData datatype'
homepage_url: http://workflow4metabolomics.org
long_description: 'Part of the W4M project: http://workflow4metabolomics.org Datatypes
  to ease the usability of W4M xcms tools'
name: rdata_xcms_datatypes
owner: lecorguille
