categories: [Metabolomics]
description: '[Metabolomics][W4M][LC-MS] XCMS R Package - Preprocessing - Correct retention time
  from different samples'
homepage_url: http://workflow4metabolomics.org
long_description: 'Part of the W4M project: http://workflow4metabolomics.org XCMS:
  http://www.bioconductor.org/packages/release/bioc/html/xcms.html Retention Time
  Correction using retcor function from xcms R package'
name: xcms_retcor
owner: lecorguille
remote_repository_url: https://github.com/workflow4metabolomics/xcms
