categories: [Metabolomics]
description: '[Metabolomics][W4M][LC-MS] XCMS R Package - Preprocessing - Group peaks from different
  samples together'
homepage_url: http://workflow4metabolomics.org
long_description: 'Part of the W4M project: http://workflow4metabolomics.org XCMS:
  http://www.bioconductor.org/packages/release/bioc/html/xcms.html Group peaks
  together across samples using overlapping m/z bins and calculation of smoothed peak
  distributions in chromatographic time.'
name: xcms_group
owner: lecorguille
remote_repository_url: https://github.com/workflow4metabolomics/xcms
